CREATE TABLE customers (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT,
    last_name TEXT,
    email TEXT,
    mobile_number TEXT,
    password TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    zip_code TEXT,
    points INTEGER DEFAULT 0 NOT NULL
);

INSERT INTO customers
(id, first_name, last_name, email, mobile_number, password)
VALUES
(0, 'Guest', 'Guest', 'guest@guest.com', '9000000', 'password');