CREATE TABLE orders (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_type TEXT,
    customer_first_name TEXT,
    customer_last_name TEXT,
    customer_mobile_number TEXT,
    customer_address TEXT,
    customer_city TEXT,
    customer_state TEXT,
    customer_zip_code TEXT,
    subtotal DECIMAL NOT NULL,
    time_placed TIMESTAMP,
    time_ready TIMESTAMP,
    date_created TIMESTAMP NOT NULL,
    customer_id BIGINT REFERENCES customers(id) ON DELETE CASCADE
);