CREATE TABLE order_items (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category TEXT,
    name TEXT,
    description TEXT,
    size TEXT,
    price DECIMAL,
    ingredients_special_request TEXT,
    special_request TEXT,
    order_id BIGINT REFERENCES orders(id) ON DELETE CASCADE
);