CREATE TABLE toppings (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    category TEXT,
    name TEXT,
    price DECIMAL,
    extra_price DECIMAL
);

INSERT INTO toppings (
    category ,name , price, extra_price
)
VALUES
(
    'Sauce',
    'Tomatoe sauce',
    1.00,
    1.00
),
(
    'Sauce',
    'Marinara sauce',
    1.00,
    1.00
),
(
    'Meats',
    'Pepperoni',
    1.00,
    1.00
),
(
    'Meats',
    'Bacon',
    1.00,
    1.00
),
(
    'Meats',
    'Sausage',
    1.00,
    1.00
),
(
    'Meats',
    'Meatballs',
    1.00,
    1.00
);